services:
  - type: web
    runtime: static
    name: vinum-sacrum
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
